[project]
name = "bomkit"
version = "0.1.0"
description = "Open-source toolkit for parsing and normalizing Bills of Materials"
authors = [{name="Ethan Rozee", email="ethanrozee01@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "openpyxl",
    "chardet",
    "pint",
    "psycopg2-binary",
    "requests"
]

[project.optional-dependencies]
mcp = ["mcp"]

[project.scripts]
bomkit = "bomkit.cli:main"
teamcenter-mcp = "bomkit.mcp.teamcenter_server:main"

[project.urls]
"Homepage" = "https://github.com/erozee1/bomkit"
"Documentation" = "https://github.com/erozee1/bomkit#readme"
"Bug Tracker" = "https://github.com/erozee1/bomkit/issues"

[tool.setuptools.packages.find]
include = ["bomkit*"]
